common:
  per_page: 5
  products_per_page: 12
orders:
  status: {open: "open", deliver: "deliver", close: "close"}
pictures:
  upload_dir: "uploads"
  accepted_files: "image/jpeg, image/gif, image/png"
  max_size: 5
  avatar_size: "128"
  avatar_small_size: "24"
mailer:
  default_mail: "no-reply@fdf-12.herokuapp.com"
index:
  max_shops: 5
  max_products: 8
comment:
  num_posts: 2
date_format: "YYYY/MM/DD"
search:
  min_results: 5
